// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frgdwxlqqnrqewcvzzkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZ2R3eGxxcW5ycWV3Y3Z6emtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDMzNzEsImV4cCI6MjA2NTMxOTM3MX0.yH1eQ4avKygXJ7C6alkK9Wm-Leybb8Cbnia6SuZhxy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);